<h1>Caravana criada</h1>
<p>Sua caravana foi inscrita, use o código abaixo para que os participantes
se inscrevam como integrantes da sua caravana. Lembre-se de que quando o
número mínimo de pessoas forem inscritas e confirmarem o pagamento sua
inscrição será quitada, mas para isso é necessário que as inscrições sejam
feitas usando o código abaixo.</p>

<h2>Código: <span style="color:green"><?php echo $this->codigoCaravana;?></span></h2>